# environment variables
environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "3"
    - nodejs_version: "4"

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set PATH=node_modules\.bin;%APPDATA%\npm;%PATH%
  - npm update -g
  - node --version
  - npm --version

test_script:
  - npm test
